//import java.util.Random; 

public class Robot {

    private String myColor;
    private String myName;
    
    private Boolean isReady;
    private double timeStart;

    private double time4low;
    private double time4outer;
    private double prob4low;
    private double prob4outer;
    private double prob4inner;
    private double time4collect;
    private double prob4collect;
    private int loadedBalls=0;
    private double prob4hang;
    private double time4hang;
    private double time2move2shoot;








    public Robot(String name, String color) {
        myColor = color;
        myName = name;
        isReady = true;
        timeStart = 0;
        time4low=2;
        time4outer=3;
        prob4low=.8;
        prob4outer=.8;
        prob4inner=.1;
        loadedBalls = 3;
        prob4hang = 1.0;
        time4hang = 10;
        time4collect = 5.0;
        prob4collect = .75;
        time2move2shoot = 10;
    }

    public String toString() {
        return myColor + myName;
    }

    public String getColor() {
        return myColor;
    }


    public Boolean isReady() {
        return isReady;
    }
    public double robotReady() {
        return timeStart;
    }
    public int action(int gameTime) {
        // return the points generated by the action
        int points = 0;
        if (loadedBalls >= 3) { // go shoot the balls
            timeStart = timeStart + time2move2shoot;
            // shoot the balls
            while (loadedBalls > 0) {
                timeStart += time4outer;
                if (Math.random() <= prob4outer) {
                    if (timeStart <=15)
                        points = points + 4;
                    else
                        points = points + 2;
                }   
                loadedBalls-=1;
            }
        }
        else {
            // pick up a ball
            if (Math.random()< prob4collect)
                loadedBalls += 1;
            timeStart += time4collect;

        }
        
        return points;
    }

}