package FRC2020GIT.InfiniteRechargeSim;

//import java.util.Random; 

public class Robot {

    private String myColor;
    private String myName;
    
    private Boolean isReady;
    private double timeStart;

    private double time4low;
    private double time4outer;
    private double prob4low;
    private double prob4outer;
    private double prob4inner;
    private double time4collect;
    private double time4collectLoader;
    private double prob4collect;
    private int loadedBalls=0;
    private double prob4hang;
    private double time4hang;
    private double time2move2shoot;








    public Robot(String name, String color) {
        myColor = color;
        myName = name;
        isReady = true;
        timeStart = 0;
        time4low=2;
        time4outer=3;
        prob4low=.8;
        prob4outer=0.8;
        prob4inner=.1;
        loadedBalls = 3;
        prob4hang = 1.0;
        time4hang = 10;
        time4collect = 5.0;
        time4collectLoader = 10.0;
        prob4collect = .25;
        time2move2shoot = 10;
    }

    public String toString() {
        return myColor + myName;
    }

    public String getColor() {
        return myColor;
    }
    public void robotReset() {
        timeStart=0;
    }

    public Boolean isReady() {
        return isReady;
    }
    public double robotReady() {
        return timeStart;
    }
    public int action(double gameTime) {
        // return the points generated by the action
        int points = 0;
        int currentCharge = FRC2020Match.getCharge(myColor);
        //if (currentCharge==0)
          //  return points;
        if (loadedBalls >= 3) { // go shoot the balls
            timeStart = timeStart + time2move2shoot;
            // shoot the balls
            while (loadedBalls > 0) {
                timeStart += time4outer;
                loadedBalls-=1;
                if (Math.random() <= prob4outer) {
                    // have scored increase appropriate charge
                    FRC2020Match.addCharge(myColor);
                    FRC2020Match.addBall2Loader(myColor);
                    

                    if (Math.random() <= prob4inner) {
                        if (timeStart <=15) {
                            points = points + 6;
                            //System.out.print(" + 6 AutoInner ");
                            }
                    else {
                            points = points + 3;
                            //System.out.print(" + 3  TeleInner ");
                        }
                            
                    }
                    if (timeStart <=15) {
                        points = points + 4;
                        //System.out.print(" + 4 AutoOuter ");
                        }
                else {
                        points = points + 2;
                        //System.out.print(" + 2  TeleOuter ");
                    }
                
                } 
                else
                    FRC2020Match.addBall2Field(); // robot missed shot
            }
        }

            
        else {
            // pick up a ball
            // start with field balls
            // determine if loader or field is more efficient
            if (FRC2020Match.getBallsOnField() > FRC2020Match.getBallsInLoader(myColor)){
                // get field balls
                if (FRC2020Match.getBallsOnField() > 0) {
                    timeStart += time4collect;
                    if (Math.random() < prob4collect){
                        loadedBalls += 1;
                        FRC2020Match.takeBallOffField();
                    }
                }
            
            }
            else {
                // get load balls
                if (FRC2020Match.getBallsInLoader(myColor)>0){
                    // load up to 5 or how many are left
                    timeStart += time4collectLoader;
            
                    while (FRC2020Match.getBallsInLoader(myColor)>0 && loadedBalls<5){
                        // load a ball
                        FRC2020Match.takeBallOutLoader(myColor);
                        loadedBalls++;
    
    
                    }
            }


            
            


                
            }
                
                
           

        }
        //System.out.println();
        return points;
    }

}